OCR_METHOD: "paddle"
LANG:
  - "ch_sim"
  - "en"
VIDEO: "demo/demo.mp4"
BOX:
  - 540
  - None
  - 100
  - 1000
VIS: false
OUT: "output/demo.srt"

SPLIT:
  METHOD: "vision"
  VISION:
    COLOR: "white"
    SRT_THRES: 1.0
    CHANGE_THRES: 5.0
    OUT_IMG: true
    OUT_SEG: false
  AUDIO:
    ASS_PATH: 'demo/demo.ass'
    MIN: 0.0
    MAX: 0.0